[WIP] feat: Add typesync rc file support
jeffijoe/typesync pull request #58
Opened 2020-10-22 14:41 UTC by Hopsken

2020-10-22 15:55 UTC, jeffijoe requested changes
This is awesome! I've added a few comments for some minor changes, but overall this looks amazing! 🙏

2020-10-22 15:55 UTC, jeffijoe commented on src/config-service.ts
> +  const { flags } = C.parseArguments(process.argv.slice(2))
Can we pass in an `argv` object rather than depend on `process.argv`? Also makes testing easier.

2020-10-22 15:55 UTC, jeffijoe commented on src/type-syncer.ts
> +          .map((section) => getPackagesFromSection(section, ignorePackages))
You can consolidate the 2 `maps` so we don't iterate more than we have to, and you can use `filterMap` from `util` to do the filtering and mapping in a single pass.

2020-10-22 15:55 UTC, jeffijoe commented on src/type-syncer.ts
> +    .map((name) => ({ name, version: section[name] }))
You can use `filterMap` from `util.ts` to do this in one pass.

2020-10-22 15:55 UTC, jeffijoe commented on src/type-syncer.ts
> +          .reduce((cur, acc) => [...cur, ...acc], [])
You can use `flat`.

```suggestion
          .flat()
```

2020-10-22 15:55 UTC, jeffijoe commented on src/util.ts
> +export function shrinkObject<T>(source: T): Required<T> {
Do you mind adding a test for this in `util.test.ts`? 😄

2020-10-22 15:55 UTC, jeffijoe commented on package.json
> +    "typescript": "^3.7.0"
Feel free to upgrade all packages (`npx npm-check -u`)

2020-10-22 15:55 UTC, jeffijoe commented on src/__tests__/config-service.test.ts
> +    process.argv = processArgv
See comment re: passing argv 😄

2020-10-24 02:45 UTC, Hopsken commented
@jeffijoe Thanks for the kind advices😄 I made some changes, please help review again.

2020-10-24 17:26 UTC, jeffijoe approved these changes

2020-10-24 17:27 UTC, jeffijoe commented
Just need you to [fix the build](https://travis-ci.com/github/jeffijoe/typesync/jobs/406406870) and then I can merge. 😄

2020-10-26 13:45 UTC, jeffijoe commented
@Hopsken I can merge once the coverage is back to 100% 😄

2020-10-29 01:05 UTC, Hopsken commented
@jeffijoe Finally, the coverage is back to 100% 😂 I learned a lot during this. Thanks very much.

2020-10-29 01:15 UTC, jeffijoe approved these changes

2020-10-29 01:15 UTC, merged

2020-10-29 13:03 UTC, jeffijoe commented
@Hopsken thank you for your PRs! Both have been merged and shipped with TypeSync 0.8! 🥳